# Permalinks
permalink:           pretty

# Setup
title:               Writings
tagline:             Incomplete Stories
url:                 http://rlamb2.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Russ Lamb
  url:               http://russelllamb.com
  email:             russell.w.lamb@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rlamb2/rlamb2.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
